### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by janbrus** [hagstovan/gluggin#1]
Should it be some code here?

Found it https://github.com/hagstovan/gluggin/tree/gh-pages

Jan Bruusgaard
Statistics Norway

**Comment by eydunn** [comment]
Hi Jan

Yes. That is the code for the original prototype, but it is not updated, so it is probably broken as the API has evolved. The url http://hagstova.fo/gluggin doesn't work anymore anyway, so you would have to use: https://hagstovan.github.io/gluggin/

You should rather look at the code under https://github.com/hagvarp

(master branch)
- hagvarp.github.io : https://hagvarp.hagstova.fo  -->  https://hagvarp.github.io 

(gh-pages branch)
- uttanrikisradid : https://hagvarp.hagstova.fo/uttanrikisradid  -->  https://hagvarp.github.io/uttanrikisradid 
- runavik : https://hagvarp.hagstova.fo/runavik  -->  https://hagvarp.github.io/runavik 
- eysturkommuna : https://hagvarp.hagstova.fo/eysturkommuna  -->  https://hagvarp.github.io/eysturkommuna 

etc.

Kind regards
Eyðun
